---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-dep-backend
spec:
  selector:
    matchLabels:
      app: backend-pod
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-pod
        tier: backend
        track: stable
    spec:
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
        - name: mysql-container
          image: "mysql:9.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: depreciation
          ports:
            - name: http
              containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-pv-storage
        - name: depreciation-app-backend
          image: "depreciation-app-backend"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dep-backend-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: dep-backend-secrets
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dep-backend-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dep-backend-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: dep-backend-secrets
                  key: DB_NAME
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: dep-backend-secrets
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: dep-backend-secrets
                  key: JWT_REFRESH_SECRET
