apiVersion: v1
kind: Secret
metadata:
  name: dep-backend-secrets
stringData:
  DB_HOST: localhost
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: root
  DB_NAME: depreciation
  JWT_ACCESS_SECRET: "Hx0xCG8/wbWfqFIoEPtvgRtSH9uUimYVGR81zeDWWr+KT322mUT/cunxPujoLtAovOk1PEON/3pBgO1TQXIrlTPae+9hwzKsmeudipWD0mylvSbQMqPi01S0Zh83mpyLGhBK1DyCFphrbIElPe16K0pt2Cb+N0zGu75WganEf8z8FXxj4FJRIGE02IyzLhl2KP1dhRePAinkNWy/1xJkqyMsZ/4VSDzvH7VhCCsrjHLLyrDE66GEPlOV8zV+ShmCQlKtrvES2EU5a07PWeUv3k8KgDsh4V+3ATOcxZpm/GR8q9bGFUeiwtzVBeEOVFjSAJ60hhuEhiWwOqXcNxHjMA=="
  JWT_REFRESH_SECRET: "2QQsyuATouB1DVbhUucQ3H50b7Ted4/rOwAdpLrBzFBhNZMPxDFWrEMfUbiXc1jJL+kVsECRgxNyU7iozyuqWXtJ67HTJWS/JNbBPk5LuiZCFtS35Y/ZaNR7aYG+u9k1+ssSe6WaaJgSZTHRjH8CCo8k96oHDA2+QLqtubQclXERAmaiK0nKQP0PZrpLUCIQND5DhOxWMUokEdfIP2AllrLxSHiuoZx8PFF/PxMKR75o44dqSlNpswqbyJ0A8kGulB9cbApNVZKMPpGmv7bXe8uVjemi9nhAIvA0M/11Pgm/6VAPXAfFhAcwPgPYxP3YBSFjGft+p3kUX7a+oqR7kQ=="
