---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-frontend
spec:
  selector:
    matchLabels:
      app: dep-pod
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: dep-pod
        tier: frontend
        track: stable
    spec:
      containers:
        - name: dep-image
          image: "depreciation-app-frontend-frontend"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
      
